### ISSUE TITLE
Use lestrrat-go/jwx instead of go-jose

### ISSUE THREAD

**Issue by sonatard** [clerk/clerk-sdk-go#198]
https://github.com/go-jose/go-jose -> https://github.com/lestrrat-go/jwx

## Why 
- https://github.com/lestrrat-go/jwx?tab=readme-ov-file#why-would-i-use-this-library
- jwx is very active in maintaining Pull Requests and issues.
- Support many protocols
- jwx code is very readable, with packages and specs well-aligned

If there are many favorable opinions, I will create a Pull Request.

**Comment by gkats** [comment]
Hey @sonatard thanks for the suggestion!

Is there any particular reason why go-jose does not work for you? We've evaluated other libraries in the past but decided to stick with go-jose for the time being. See #105 for more info.

**Comment by sonatard** [comment]
@gkats Thank you for your reply!
Our project does not have issues running with go-jose. However, JWT libraries require careful attention to vulnerabilities. Libraries that are widely used and actively maintained tend to address vulnerability issues more effectively. Additionally, a high-quality code base makes it easier to contribute, whether it's to add needed features or to address vulnerabilities.

Additionally, when we directly handle JWTs, we use jwx for the reasons mentioned above. This is a matter of our convenience,  we aim to minimize reliance on external libraries as much as possible.

**Comment by gkats** [comment]
I see. Thanks for elaborating further.

I agree about all the dangers of using unmaintained libraries. It was my impression that go-jose is still actively maintained and transferred to [another organization in github](https://github.com/go-jose/go-jose).

All points taken under consideration, I believe we'll keep things as-is for the time being but perhaps we should keep monitoring the evolution of the two libraries.

I'll close this issue for now, since it's not on our roadmap but it's not swept under the rag or forgotten. 

We'll make sure we switch implementations in case of vulnerabilities that might be not patched in go-jose.
